use bevy::prelude::*;
use bevy_dlc::DlcPack;
use bevy_dlc::prelude::*;

// `example.slicense` and `example.pubkey` are both generated by `bevy-dlc generate --product example`

#[derive(Asset, Reflect)]
struct TextAsset(String);

fn main() -> AppExit {
    // DO NOT USE ABCD... as your choice of secure key. This is just a placeholder for the example.
    // This is the RECOMMENDED approach:
    // Create cryptographically secure license key that can't be decrypted from your compiled binary (game).
    secure::include_secure_str_aes!("example.slicense", "ABCDEFGHIJKLMNOPQRSTUVWXYZ012345", "example_license");

    let dlc_key = DlcKey::public(include_str!("../../example.pubkey")).expect("invalid example pubkey");
    let signedlicense = SignedLicense::from(get_example_license());

    App::new()
        .add_plugins(DefaultPlugins)
        .add_plugins(DlcPlugin::new(
            Product::from("example"),
            dlc_key,
            signedlicense,
        ))
        .init_asset::<TextAsset>()
        .register_dlc_type::<TextAsset>()
        .add_systems(Startup, startup)
        .add_systems(
            Update,
            show_dlc_content.run_if(is_dlc_loaded("expansionA")),
        )
        .run()
}

#[allow(unused)]
#[derive(Component)]
struct LoadedPack(Handle<DlcPack>);

fn startup(asset_server: Res<AssetServer>, mut commands: Commands) {
    let handle = asset_server.load::<DlcPack>("expansionA.dlcpack");
    commands.spawn((Camera2d, LoadedPack(handle)));
}

fn show_dlc_content(
    dlc_packs: Res<Assets<DlcPack>>,
    asset_server: Res<AssetServer>,
    mut commands: Commands,
    query: Query<(Entity, &LoadedPack)>,
) {
    for (entity, loaded) in query.iter() {
        match dlc_packs.get(&loaded.0) {
            Some(pack) => {
                if pack.entries().is_empty() {
                    info!("DlcPack asset loaded but contains 0 entries — waiting...");
                    return;
                }
                for entry in pack.entries() {
                    info!("Spawning sprite for DLC entry: {}", entry.path());
                    let img: Handle<Image> = asset_server.load(entry.path());
                    commands.spawn(Sprite::from_image(img));
                }
                // prevent re-running/spawning again
                commands.entity(entity).remove::<LoadedPack>();
            }
            None => {
                info!("DlcPack asset not ready yet for handle: {:?}", loaded.0);
                return;
            }
        }
    }
}
